### ISSUE TITLE
npm run build  报错

### ISSUE THREAD

**Issue by liruiqing** [TencentCloud/chat-uikit-react#10]
![image](https://user-images.githubusercontent.com/9715654/228405441-809ba288-56af-4853-969c-ebfd8c1461a9.png)
node 16  node 14 都试了，根本无法build，真是无语了

**Comment by liruiqing** [comment]
拜托你们提交项目，把 lock 文件提交一下，不管是 package-lock.json 或者 yarn.lock 文件，只要不提交这些lock文件的，项目时间长了 肯定启动不了， 项目依赖的那些 npm包的版本号规范，压根就没人遵守，很多中版本，甚至小版本都不遵守向前兼容，更新的无比随意，  就这样你们还不提交 lock文件，就这样你们还不提交 lock文件，就这样你们还不提交 lock文件。。。。。。

**Comment by EricWong1994** [comment]
> 拜托你们提交项目，把 lock 文件提交一下，不管是 package-lock.json 或者 yarn.lock 文件，只要不提交这些lock文件的，项目时间长了 肯定启动不了， 项目依赖的那些 npm包的版本号规范，压根就没人遵守，很多中版本，甚至小版本都不遵守向前兼容，更新的无比随意， 就这样你们还不提交 lock文件，就这样你们还不提交 lock文件，就这样你们还不提交 lock文件。。。。。。

我连npm run start都会报错。。 Cannot find module '@tencentcloud/chat-uikit-react'

**Comment by dawnrking** [comment]
> 

感谢您的反馈!

**Comment by dawnrking** [comment]
> 拜托你们提交项目，把 lock 文件提交一下，不管是 package-lock.json 或者 yarn.lock 文件，只要不提交这些lock文件的，项目时间长了 肯定启动不了， 项目依赖的那些 npm包的版本号规范，压根就没人遵守，很多中版本，甚至小版本都不遵守向前兼容，更新的无比随意， 就这样你们还不提交 lock文件，就这样你们还不提交 lock文件，就这样你们还不提交 lock文件。。。。。。

感谢您的反馈!
新版本已添加 package-lock.json
