### ISSUE TITLE
聊天上传一张图片，再发一行文字,会一起删除

### ISSUE THREAD

**Issue by lovehebe330** [TencentCloud/chat-uikit-react#14]
![image](https://user-images.githubusercontent.com/20655248/236423155-11f7a5eb-5227-45e3-8bd9-2a9555b763aa.png)
先上传一张图片，再发送一行文字，点击删除图片，底下的文字也会一起删掉。

**Comment by dawnrking** [comment]
感谢您的反馈！！！
  这边测试没有发现，可以重新跑通一下，提供一下日志， 谢谢
