### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by ctliz** [TencentCloud/chat-uikit-react#15]
运行环境：
macos m1 版本 13.3.1 
nodejs版本 v18.15.0

复现：
git clone https://github.com/TencentCloud/chat-uikit-react
cd chat-uikit-react
npm install && cd examples/sample-chat && npm install
npm run start 

报错截图:
![image](https://github.com/TencentCloud/chat-uikit-react/assets/26066413/c4b0f2ac-daf4-43f7-8cad-5e8b579ce94b)

**Comment by dawnrking** [comment]
感谢您的反馈!
最新版本已修复

**Comment by caslanbigeyes** [comment]
请问修复了么？
<img width="781" alt="image" src="https://github.com/TencentCloud/chat-uikit-react/assets/53009552/114bc4ce-9c6c-4f7f-b63e-40393e138fa6">
