### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by Huchangzhi** [TencentCloud/chat-uikit-react#31]
node16和20都这样

![屏幕截图 2024-02-07 161235](https://github.com/TencentCloud/chat-uikit-react/assets/138838812/ba9084a3-7584-4922-8615-1ef66efd5a62)
![屏幕截图 2024-02-07 161406](https://github.com/TencentCloud/chat-uikit-react/assets/138838812/979bc55d-41d3-4ad5-8827-aec2274514cf)
![屏幕截图 2024-02-07 161525](https://github.com/TencentCloud/chat-uikit-react/assets/138838812/3c449e97-e9f5-4c43-8355-d4d57a05f7a8)

**Comment by Ashster** [comment]
您好，感谢反馈，这个问题已在 v2.2.9 修复，您可以升级 v2.2.9 解决
