### ISSUE TITLE
v2.2.6直接将整个TUIKit删除了，H5的例子没有了吗？

### ISSUE THREAD

**Issue by ArcherGu** [TencentCloud/chat-uikit-react#48]
从提交记录看，你们这次的版本升级改动挺大，移除了TUIKit，包括里面的 RenderForH5 组件。现在是否有H5的例子可供参考？

**Comment by Ashster** [comment]
您好，H5与PC的示例代码都在 examples/sample-chat/src/pages/Chat/index.tsx 中，您可以参考下

**Comment by Ashster** [comment]
https://github.com/TencentCloud/chat-uikit-react/blob/main/examples/sample-chat/src/pages/Chat/index.tsx
