### ISSUE TITLE
提示重复登陆，userID 从哪获取呢

### ISSUE THREAD

**Issue by Zian502** [TencentCloud/chat-uikit-react#5]
![image](https://user-images.githubusercontent.com/26033663/218023640-32b959f1-5849-4454-87dc-58cc96308f77.png)

**Comment by jiushu531** [comment]
userID 是用户自己设置的，在`chat-uikit-react/examples/sample-chat/src/demo/SampleChat.tsx` 文件中可以自行修改，这里 
 demo 写死的固定 ID ‘xxx’。

**Comment by dawnrking** [comment]
> chat-uikit-react/examples/sample-chat

感谢您的反馈！可以把 @tencentcloud/chat-uikit-react 升级到 v1.0.2 版本

**Comment by mankeheaven** [comment]
@jiushu531 你这个思路是不对的，严格模式触发多次就是为了让你写代码注意和处理副作用的影响。demo中应该处理一下这个useEffect  setTim这块。默认就应该按照render twice的方式来写你只login一次
